Feature/21
rice-apps/owlmart pull request #30
Opened 2023-07-16 04:57 UTC by isauros1000

First attempt at the Post Mutation!

2023-07-23 15:47 UTC, DanielCufino requested changes
Looking good! A couple of nits in the comments

2023-07-23 15:47 UTC, DanielCufino commented on server/graphql/resolvers/listing.js
> +    createDog: async (_, { title, description, price, active=true, pictures, pickup, category }, context) => {
This should be createListing

2023-07-23 15:47 UTC, DanielCufino commented on server/graphql/resolvers/listing.js
> +
In the future we're going to want to add authentication handling. I.E. Authenticating whether the using logged in is the user trying to create this listing. This is fine for now though it's not a huge priority

2023-07-23 15:47 UTC, DanielCufino commented on server/models/Listing.js
> +const Image = require('./Image.js').schema;
This may be the issue that you're running into. Try removing the .schema

2023-07-23 15:47 UTC, DanielCufino commented on server/models/Listing.js
>    pictures: [Image],
On second thought, we probably shouldn't refer to entire Image schema objects within a listing but instead the object ID's of the images.

Try this instead:

`pictures: [{ type: Schema.Types.ObjectId, ref: 'Image' }]`

2023-07-23 15:47 UTC, DanielCufino commented on server/models/Listing.js
> -module.exports = Listing;
I would shy away from this and just leave it as a one-liner:

`module.exports = model('Listing', listingSchema);`

2023-07-23 15:47 UTC, DanielCufino commented on server/models/Listing.js
> -module.exports = Listing;
I think there are multiple occurences of this in the PR

2023-07-24 01:53 UTC, isauros1000 commented on server/models/Listing.js
>    pictures: [Image],
good idea! I had seen this in a stack exchange when I was debugging but I wasn't quite sure that it meant but thank you for explaining.

2023-07-24 01:59 UTC, isauros1000 commented on server/graphql/resolvers/listing.js
> +
In the future, how would we go about this ? Add a user parameter and look up to see if they're logged in?

2023-07-25 21:23 UTC, DanielCufino commented on server/graphql/resolvers/listing.js
> +
The context should contain the JWT token of a user that we can decode and then find a user by to compare against

2023-08-01 14:35 UTC, DanielCufino reviewed
looks good!

2023-08-01 14:35 UTC, DanielCufino approved these changes
Great work!

2023-08-01 21:36 UTC, merged