Feature/24
rice-apps/owlmart pull request #31
Opened 2023-07-16 20:23 UTC by alelucena

MongoDB schema is complete along with added validation.

2023-07-16 20:30 UTC, DanielCufino requested changes
Overall looks good to me! Just one nit that I left a comment on if you could address it. Great work

2023-07-16 20:30 UTC, DanielCufino commented on server/models/User.js
> +  _id: Schema.Types.ObjectId,
I don't think you're required to add the _id field for mongoose schemas. It should be automatically created and populated for you using Mongoose. Could you delete this?

2023-07-16 21:59 UTC, alelucena commented on server/models/User.js
> +  _id: Schema.Types.ObjectId,
After our last meeting (Thursday), I changed this feature in feature 25 instead of feature 24. I have pushed my latest updates.

2023-07-25 20:05 UTC, alelucena commented
Please review branch again.

2023-07-25 21:25 UTC, DanielCufino approved these changes

2023-08-01 16:07 UTC, merged