Feature/25
rice-apps/owlmart pull request #32
Opened 2023-07-16 22:00 UTC by alelucena

Resolved errors (changed typedefs) and improved user validation. For ease, merge feature 25 as it should contain both features 24 and 25.

2023-07-23 15:58 UTC, DanielCufino requested changes
Looking good just a couple small things

2023-07-23 15:58 UTC, DanielCufino commented on server/graphql/resolvers/user.js
> +//var url = MONGODB
remove unnecessary commented lines

2023-07-23 15:58 UTC, DanielCufino commented on server/graphql/resolvers/user.js
> +        newUser.email = email
I'd recommend adding some form of user email validation. 

Trying looking into this resourcce: https://www.abstractapi.com/tools/email-regex-guide

Also I'd also recommend validating by checking the email ends in `@rice.edu`

2023-07-25 20:05 UTC, alelucena commented
Please review branch again.

2023-07-25 21:25 UTC, DanielCufino approved these changes
LGTM!

2023-08-01 14:43 UTC, DanielCufino commented
Please merge changes

2023-08-01 16:20 UTC, merged